[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# xylo = "^0.3.1"
pagekey-xylo = { path="/home/steve/repos/xylo" }
