name: Test and release Xylo package

on:
  push:
    branches-ignore:
      - 'refs/tags/*'

jobs:

  version:
    uses: pagekey/semver/.github/workflows/semver.yml@main  

  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: stable
      
      - name: Cargo test
        run: cargo test

  mirror:
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits instead of just current one
      - name: Create remote and push
        env:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.com/pagekey/semver.git
          git remote remove origin
          git push --mirror gitlab
